using PrismFanlight.Authoring;
using UnityEditor;

namespace PrismFanlight.Editor
{
    [CustomEditor(typeof(FanlightLayoutBakeArtifact))]
    internal sealed class FanlightLayoutBakeArtifactEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            EditorGUILayout.HelpBox("Generated by its parent Fanlight Layout Asset. Rebuild or bake the parent asset to update this artifact.", MessageType.Info);
        }
    }
}
